export class Constants {
    static ACTIVITY_CEO_PRESENTATION = "CEO_PRESENTATION";
    static ACTIVITY_COMPLETE_PROFILE = "COMPLETE_PROFILE";
    static ACTIVITY_FIRST_DAY_INFORMATION = "FIRST_DAY_INFORMATION";
    static ACTIVITY_KNOW_YOUR_TEAM = "KNOW_YOUR_TEAM";
    static ACTIVITY_ON_SITE_INDUCTION = "ON_SITE_INDUCTION";
    static ACTIVITY_REMOTE_INDUCTION = "REMOTE_INDUCTION";
    static ACTIVITY_INDUCTION_ELEARNING = "INDUCTION_ELEARNING";
  
    static ELEARNING_CONTENT_CARD_TYPE_QUESTION="QUESTION";
    static ELEARNING_CONTENT_CARD_TYPE_TEXT="TEXT";
    static ELEARNING_CONTENT_CARD_TYPE_VIDEO="VIDEO";
}
