onboarding:
  files:
    folder: /home/server/onboarding/files
    url:
      file: https://myanddes.anddes.com:8443/files/public/{fileId}/filename/{filename}
      video: https://myanddes.anddes.com:8443/files/public/{fileId}/video/{name}
spring:
  config:
    import: optional:file:./config/application-external.yml
    ##import: optional:file:/home/server/onboarding/backend//config/application-external.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          algorithm: RS256
          issuer-uri: https://login.microsoftonline.com/2e7c2c87-0ed1-48f9-a17a-76261219bf54/v2.0
          jwk-set-uri: https://login.microsoftonline.com/2e7c2c87-0ed1-48f9-a17a-76261219bf54/discovery/keys
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://172.16.16.50:5432/myanddes_onboarding?autoReconnect=true
    username: my_anddes_test
    password: Anddes2024$$

    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1

    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.office365.com
    port: 587
    username: notificaciones.anddes@anddes.com
    password: notifica$$2025
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true