export const Constants = {
    ACTIVITY_CEO_PRESENTATION: "CEO_PRESENTATION",
    ACTIVITY_COMPLETE_PROFILE: "COMPLETE_PROFILE",
    ACTIVITY_FIRST_DAY_INFORMATION: "FIRST_DAY_INFORMATION",
    ACTIVITY_KNOW_YOUR_TEAM: "KNOW_YOUR_TEAM",
    ACTIVITY_ON_SITE_INDUCTION: "ON_SITE_INDUCTION",
    ACTIVITY_REMOTE_INDUCTION: "REMOTE_INDUCTION",
    ACTIVITY_INDUCTION_ELEARNING: "INDUCTION_ELEARNING",
    
    ACTIVITY_PARENT_BEFORE: "BEFORE",
    ACTIVITY_PARENT_FIRST_DAY: "FIRST_DAY",
    ACTIVITY_PARENT_FIRST_WEEK: "FIRST_WEEK",

    FIRST_DAY_INFORMATION_ITEM_TYPE_DEFAULT: "DEFAULT",
    FIRST_DAY_INFORMATION_ITEM_TYPE_OTHER_SOURCES: "OTHER_SOURCES",

    ELEARNING_CONTENT_CARD_TYPE_QUESTION:"QUESTION",
    ELEARNING_CONTENT_CARD_TYPE_TEXT:"TEXT",
    ELEARNING_CONTENT_CARD_TYPE_VIDEO:"VIDEO"
} as const;